from abc import ABC, abstractmethod
from typing import Any, Iterable, Optional

class CompanyRepository(ABC):
    @abstractmethod
    def list_by_company(self, company_id: str) -> Iterable[dict]: ...

class MasterRepository(ABC):
    @abstractmethod
    def list_by_company(self, kind: str, company_id: str) -> Iterable[dict]: ...

class InvoiceRepository(ABC):
    @abstractmethod
    def create(self, row: dict) -> dict: ...
    @abstractmethod
    def get(self, invoice_id: str) -> Optional[dict]: ...
    @abstractmethod
    def list_by_company(self, company_id: str, period: Optional[str] = None) -> Iterable[dict]: ...
    @abstractmethod
    def save(self, row: dict) -> dict: ...

class ApprovalRepository(ABC):
    @abstractmethod
    def get(self, invoice_id: str) -> Optional[dict]: ...
    @abstractmethod
    def save(self, approval: dict) -> dict: ...
    @abstractmethod
    def list_by_company(self, company_id: str, invoice_lookup) -> Iterable[dict]: ...

class PurchaseRepository(ABC):
    @abstractmethod
    def list_by_company(self, company_id: str, period: Optional[str] = None) -> Iterable[dict]: ...
    @abstractmethod
    def create(self, row: dict) -> dict: ...

class ReconciliationRepository(ABC):
    @abstractmethod
    def list_2b(self, company_id: str, period: str) -> Iterable[dict]: ...
    @abstractmethod
    def upsert_2b(self, row: dict) -> dict: ...

class AuditRepository(ABC):
    @abstractmethod
    def append(self, row: dict) -> dict: ...
    @abstractmethod
    def list_by_company(self, company_id: str) -> Iterable[dict]: ...
